#!/usr/bin/env python2.7

import fileinput
import sys
from argparse import ArgumentParser
from hipchat_msg_parser import MsgParser

def process_args():
    USAGE_STR="""
    %(prog)s [options] < [FILE-NAME]
    - or -
    echo [MESSAGE] | %(prog)s [options]"""
    parser = ArgumentParser(description='Parse HipChat messages.', usage=USAGE_STR)

    return parser


def main():
    parser = process_args()
    args = parser.parse_args()

    for line in fileinput.input():
        msg = line.rstrip()
        if len(msg):
            mp = MsgParser()
            print "Input: ", msg
            print "Ouput:"
            mp.tokenize(msg)
            ret = mp.genparse()
            print ret
            print


if __name__ == "__main__":
    sys.exit(main())
